name: monitoramento_saude_familiar
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
      sdk: ^3.8.1

dependencies:
      flutter:
            sdk: flutter

      cupertino_icons: ^1.0.8
      date_picker_timeline: ^1.2.7
      carousel_slider: ^5.1.1
      fl_chart: ^0.63.0
      syncfusion_flutter_gauges: ^31.2.5
      flutter_speed_dial: ^7.0.0
      hive: ^2.2.3
      hive_flutter: ^1.1.0
      path_provider: ^2.1.2
      csv: ^5.0.1
      flutter_local_notifications: ^17.2.0
      timezone: ^0.9.3
      flutter_launcher_icons: ^0.14.4

dev_dependencies:
      flutter_test:
            sdk: flutter
      flutter_lints: ^5.0.0

flutter:
      uses-material-design: true
      assets:
            - assets/data/medication_2025.csv

# ðŸ‘‡ ESTA PARTE DEVE FICAR AQUI (fora de dev_dependencies)
flutter_launcher_icons:
      android: true
      ios: true
      image_path: "assets/icons/icon.png"
      adaptive_icon_background: "#FFFFFF"
      adaptive_icon_foreground: "assets/icons/icon.png"
